import tseslint from 'typescript-eslint';

/**
 * One lint configuration for the whole monorepo.
 *
 * There was a shared preset in tooling/eslint that nothing extended, so
 * `turbo run lint` checked nothing at all — the engineering rules the team
 * agreed on had no mechanism behind them. This is that mechanism.
 *
 * Deliberately not type-aware: a type-aware pass needs a project per workspace
 * and is slow enough that people stop running it. The rules here are the ones
 * that can be checked from syntax alone, and `pnpm typecheck` already runs the
 * compiler with strict, noUncheckedIndexedAccess and exactOptionalPropertyTypes.
 */
export default tseslint.config(
  {
    ignores: [
      '**/node_modules/**',
      '**/dist/**',
      '**/.next/**',
      '**/out/**',
      '**/*.config.js',
      '**/*.config.mjs',
      '**/*.config.ts',
      // Tool configuration that has to be CommonJS for the tool to read it.
      '**/.prettierrc.js',
      '**/postcss.config.js',
      // Generated by Next; not ours to lint.
      '**/next-env.d.ts',
      // Prisma's seed runs under plain node and predates the TypeScript setup.
      'apps/api/prisma/**',
      // Verification scripts are plain node with no build step.
      'scripts/**',
    ],
  },

  ...tseslint.configs.recommended,

  {
    files: ['**/*.ts', '**/*.tsx'],
    rules: {
      // ── Type safety ──────────────────────────────────────────────────────
      // Escape hatches are the thing the compiler cannot warn about: they
      // silence it. There is exactly one justified `any` in the codebase, and
      // it carries a written reason, so an inline disable is the right way to
      // add another.
      '@typescript-eslint/no-explicit-any': 'error',
      '@typescript-eslint/ban-ts-comment': [
        'error',
        { 'ts-expect-error': 'allow-with-description', 'ts-ignore': true },
      ],
      // `x as unknown as Y` asserts a type the compiler actively disagrees
      // with. Sometimes genuinely unavoidable at a boundary — a Prisma JSON
      // column is the honest case, and apps/api/src/common/json.ts is where
      // that boundary is named — but never something to reach for silently.
      //
      // A warning rather than an error, deliberately. There are fifteen of
      // these already, most of them predating this configuration, and they are
      // the type-safety debt the roadmap pays down when the section documents
      // get schemas. Failing the build on them today would mean turning the
      // rule off, which is how a rule stops being read at all.
      'no-restricted-syntax': [
        'warn',
        {
          selector: 'TSAsExpression > TSAsExpression > TSUnknownKeyword',
          message:
            'Double assertion through `unknown` defeats the type checker. ' +
            'Narrow the value, use fromJson/toJson at a JSON column, or ' +
            'disable this line with a reason.',
        },
      ],

      // ── Consistency ──────────────────────────────────────────────────────
      '@typescript-eslint/consistent-type-imports': [
        'error',
        { prefer: 'type-imports', fixStyle: 'inline-type-imports' },
      ],
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],

      // ── Silent failure ───────────────────────────────────────────────────
      // An empty block containing a comment passes: swallowing an error on
      // purpose is fine, swallowing it without saying why is not.
      'no-empty': ['error', { allowEmptyCatch: false }],

      // Logging is how the server explains itself; the browser is not.
      'no-console': ['warn', { allow: ['warn', 'error'] }],
    },
  },

  {
    files: ['apps/api/**/*.ts'],
    rules: {
      // Nest resolves constructor dependencies from the emitted parameter
      // metadata, which only exists if the class was imported as a value.
      // `import type { PrismaService }` compiles and then fails at runtime with
      // an unresolvable dependency, so this rule cannot run against a codebase
      // using constructor injection.
      '@typescript-eslint/consistent-type-imports': 'off',
      // The server's log is how it explains itself.
      'no-console': 'off',
    },
  },
);
